### ISSUE TITLE
Mejoras visuales

### ISSUE THREAD

**Issue by Miangame** [susomejias/SusoTools-Linux#1]
Se puede dejar el menú como varios submenús más pequeños. Pienso que es algo más visual y funcional. Te adjunto el archivo.
[SusoTools-Linux-master.zip](https://github.com/susomejias/SusoTools-Linux/files/1254401/SusoTools-Linux-master.zip)

**Comment by susomejias** [comment]
Perfecto lo añado, muchas gracias jajaja :+1:
